// export const INVALIDATE_USER = 'INVALIDATE_USER';

export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS';

export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS';

export const SIGNED_IN = 'SIGNED_IN';