export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS';

export const RECEIVE_ALL_TRANSACTIONS = 'RECEIVE_ALL_TRANSACTIONS';
export const REQUEST_ALL_TRANSACTIONS = 'REQUEST_ALL_TRANSACTIONS';

export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
